#
# ObjectWindows - (C) Copyright 1992 by Borland International
#

!if !$d(BCROOT)
!include "..\bcroot.inc"
!endif

!include "..\..\examples\makefile.inc"

ttfont.exe: turboc.cfg ttfont.obj ttfont.res
     $(TLINK) $(LFLAGS) $(BCLIBDIR)\c0w$(MODEL)  ttfont,ttfont,,@&&!
$(OWLLIBS) $(STDLIBS)
!,$(OWLROOT)\lib\owl.def
     $(RC) -31 -K ttfont.res ttfont.exe

turboc.cfg: makefile ..\..\examples\makefile.inc
	echo -I$(INCLUDE) >turboc.cfg

clean:
	del *.obj
	del *.exe
	del *.res
	del *.dll
	del *.lib
	del *.map
	del *.sym
        del *.dsk
        del turboc.cfg

