#
# ObjectWindows - (C) Copyright 1992 by Borland International
#

!if !$d(BCROOT)
!include "..\bcroot.inc"
!endif

!include "..\..\examples\makefile.inc"

owlscrn.scr: turboc.cfg tscrnsav.obj owlscrn.obj owlscrn.res
     $(TLINK) $(LFLAGS) $(BCLIBDIR)\c0w$(MODEL) owlscrn tscrnsav,owlscrn.scr,,@&&!
$(OWLLIBS) $(STDLIBS)
!,owlscrn.def
     $(RC) -31 -K owlscrn.res owlscrn.scr

turboc.cfg: makefile ..\..\examples\makefile.inc
        echo -I$(INCLUDE) >turboc.cfg

clean:
        del *.obj
        del *.exe
        del *.res
        del *.dll
        del *.lib
        del *.map
        del *.sym
        del *.dsk
        del *.scr
        del turboc.cfg

